### ISSUE TITLE
Container package?

### ISSUE THREAD

**Issue by rothgar** [aws/aws-imds-packet-analyzer#1]
It would be great if this could be packaged as a container and available on ECR Public so we can run it with docker on a local machine or deploy it as a daemon in Kubernetes or ECS.

Would that be possible?

**Comment by geanboegman** [comment]
No activity and I doubt this would be possible as it needs to run inside the instance kernel.

**Comment by jhmartin** [comment]
Would it work to run it as a privileged container using the host network and pid namespace?

**Comment by JBOClara** [comment]
daemonset :
```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: aws-imds-packet-analyzer
  namespace: monitoring
  labels:
    app: aws-imds-packet-analyzer
spec:
  selector:
    matchLabels:
      app: aws-imds-packet-analyzer
  template:
    metadata:
      labels:
        app: aws-imds-packet-analyzer
    spec:
      hostNetwork: true
      containers:
      - name: analyzer
        image: <YOUR_REGISTRY>/aws-imds-packet-analyzer:latest
        securityContext:
          privileged: true
        volumeMounts:
        - name: sys
          mountPath: /sys
          readOnly: true
        - name: src
          mountPath: /usr/src
          readOnly: true
        - name: modules
          mountPath: /lib/modules
          readOnly: true
        - name: proc
          mountPath: /proc
          readOnly: true
      volumes:
      - name: sys
        hostPath:
          path: /sys
      - name: src
        hostPath:
          path: /usr/src
      - name: modules
        hostPath:
          path: /lib/modules
      - name: proc
        hostPath:
          path: /proc
```

Dockerfile
```
FROM ubuntu:22.04

# Install dependencies
RUN apt-get update && apt-get install -y \
    bison build-essential cmake flex git libedit-dev \
    libllvm14 llvm-14-dev libclang-14-dev python3 zlib1g-dev \
    libelf-dev libfl-dev python3-distutils python3-setuptools \
    zip && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
# Clone and build BCC with proper installation steps
WORKDIR /home/ubuntu

RUN git clone https://github.com/iovisor/bcc.git && \
    mkdir bcc/build && cd bcc/build && \
    cmake .. && \
    make && \
    make install && \
    # Build Python3 binding specifically
    cmake -DPYTHON_CMD=python3 .. && \
    cd src/python/ && \
    make && \
    make install

USER root

WORKDIR /home/ubuntu

RUN git clone https://github.com/aws/aws-imds-packet-analyzer.git

# Set environment variables
ENV LD_PRELOAD=/home/ubuntu/bcc/build/src/cc/libbcc.so.0
ENV PYTHONPATH=/home/ubuntu/bcc/build/src/python

# Use CMD instead of ENTRYPOINT for more flexibility
CMD ["python3", "/home/ubuntu/aws-imds-packet-analyzer/src/imds_snoop.py"]
```

It works fine to me
